badges
prototype2010/test-guru pull request #18
Opened 2023-07-03 08:17 UTC by prototype2010

2023-07-03 13:59 UTC, VidgarVii requested changes

2023-07-03 13:59 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +      Badge.check_badges_available(@test_passage)
в данном решении можно постоянно обновлять данную страницу результата и получать баджи. Либо нагружать систему. 
Бадж следует выдавать после завершения теста. А он завершается не тут

2023-07-04 05:15 UTC, prototype2010 commented on app/controllers/test_passages_controller.rb
> +      Badge.check_badges_available(@test_passage)
обновлять и получать бажди не получится. Загляни в метод check_badges_available

2023-07-04 14:27 UTC, VidgarVii requested changes

2023-07-04 14:27 UTC, VidgarVii commented on app/controllers/admin/badges_controller.rb
> +    params.require(:badge).permit(:name, :description, :url, :category_id, :circumstance, :level)
Админ при создании баджа должен выбирать тип правила (Категория/лвл и пр) И параметр правила (Ид категории/лвл уровня и пр.) 
В ДЗ заданы 3 типа правила. Но учти что система должна быть готова к масштабировании. И правил может быть сколько угодно.
Где то типы правил надо складывать без раздутия моделей и классов

***
badge_params
params.require(:badge).permit(:title, :image, :rule, :level, :category_id, :test_id, :first_try)

вторая ошибка в проектировании самой таблицы. При заполнении таблицы у тебя получится почти пусты колонки :level, :category_id, :test_id, :first_try
Такой подход считается очень плохим. Если колонка почти всегда пустая, то скорей всего она не нужна

2023-07-04 14:27 UTC, VidgarVii commented on app/models/badge.rb
> +         %i[all_from_category all_perfectly tests_passed_3 tests_passed_5 all_tests_done all_within_level]
отличное решение использовать ENUM, Но с отступами надо что-то делать

2023-07-04 14:27 UTC, VidgarVii commented on app/models/badge.rb
> +  belongs_to :category, optional: true
1 belongs_to и has_many разделяют пустыми строками. Такое разделение кода на логические блоки.
Пример оформления модели можно посмотреть тут https://github.com/rubocop/rails-style-guide#macro-style-methods
2 рекомендуется сначала писать все `belongs_to`, а уже после них все `has_many` ассоциации

2023-07-04 14:27 UTC, VidgarVii commented on app/models/badge.rb
> +  validates :level, numericality: { only_integer: true, greater_than: 0 }
если еще 10ток правил добавить, сколько тут появятся валидаций? На лицо проблема конструирования класса

2023-07-04 14:27 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +      BadgeService.new(@test_passage).check_badges_available
вызов сервиса есть. А где код самого сервиса?)

2023-07-05 14:18 UTC, VidgarVii requested changes

2023-07-09 17:00 UTC, merged