seeds, instance and class methods
prototype2010/test-guru pull request #2
Opened 2023-05-07 08:50 UTC by prototype2010

2023-05-08 14:51 UTC, VidgarVii requested changes

2023-05-08 14:51 UTC, VidgarVii commented on app/models/test.rb
> +  scope :by_category_title, ->(category_title) do
1. В ТЗ ожидается метод класса, а не скоуп
2. По ТЗ метод должен возвращать массив названий всех тестов

2023-05-08 14:51 UTC, VidgarVii commented on app/models/test.rb
> +    Test.where(category_id: Category.where("title = :title", title: category_title))
можно (и рекомендуется)  писать так:
```ruby
joins(...)...
```
т.е. без явного указания объекта у которого вызывается метод
потому что в данном случае объектом является класс `Test` и ему равен `self` внутри класс-метода
по дефолту, при вызове метода без указания объекта он вызывается у `self`, т.е. в текущем варианте как раз у `Test`

2023-05-08 14:51 UTC, VidgarVii commented on app/models/test.rb
> +    Test.where(category_id: Category.where("title = :title", title: category_title))
использовать под запрос для поиска категорий не самый оптимальный вариант. Они работают не очень быстро.
В данном случаи лучше подойдёт джойн

2023-05-08 14:51 UTC, VidgarVii commented on app/models/test.rb
> +    Test.where(category_id: Category.where("title = :title", title: category_title))
`title = :title", title: category_title`
аргументы в виде хеш смотрятся и читаются лучше

2023-05-08 14:51 UTC, VidgarVii commented on app/models/user.rb
> +    Test.where("user_id = :id AND level = :level", {id: id, level: level})
Надо учесть ряд моментов:
1 юзер может прохадить один и тот же тест несколько раз
2 Разные юзеры могут проходить любые тесты
связь belongs_to выбрана не верно.

2023-05-08 14:51 UTC, VidgarVii commented on db/seeds.rb
> +  category = Category.create(title: "Category #{category_number}")
лучше использовать `create!` - метод бросит исключение, если запись не создастся
сразу будет видно, если что-то пошло не так

2023-05-08 14:51 UTC, VidgarVii commented on db/seeds.rb
> +10.times do |category_number|
динамическое создание сидов не самый лучший способ. Потом тяжело будет всё это тестировать и отлаживать

2023-05-08 14:51 UTC, VidgarVii commented on db/seeds.rb
> +      Answer.create(is_correct: true, question_id: question.id)
is_correct
не очень удачное название. Я бы сказал такое ни где в руби не используется. Для булевых полей не используют нотацию is_

2023-05-08 18:40 UTC, prototype2010 commented on app/models/user.rb
> +    Test.where("user_id = :id AND level = :level", {id: id, level: level})
> Надо учесть ряд моментов: 1 юзер может прохадить один и тот же тест несколько раз 2 Разные юзеры могут проходить любые тесты связь belongs_to выбрана не верно.

я тоже так думал сделать, не пойму как я прошел  предыдущее ревъю ?

2023-05-09 13:13 UTC, prototype2010 commented on db/seeds.rb
> +10.times do |category_number|
как лучше сиды создвать, если не в factory_bot ?

2023-05-10 06:39 UTC, VidgarVii requested changes

2023-05-10 06:39 UTC, VidgarVii commented on app/models/answer.rb
> +  belongs_to :user
ассоциации позже будут в курсе
пока лучше убери их из моделей, чтобы они не отвлекали. Тем более они объявлены не верно.
Нам на данном этапе внешних ключей в таблицах вполне достаточно ближайшие пару уроков нужно будет ручками конструировать запросы, чтобы лучше понять, как ассоциации работают, а потом уже будем использовать ассоциации

2023-05-10 06:39 UTC, VidgarVii commented on app/models/test.rb
> +        .where('categories.title': category_title)
В документации такого нет. Тут всё не много проще
{ categories: { title: category_title } 
.order(title: :desc)} 
.pluck(:title')

2023-05-10 06:39 UTC, VidgarVii commented on app/models/answer.rb
> +  belongs_to :user
ответы принадлежат только вопросам. Знать о юзерах им не стоит

2023-05-10 06:39 UTC, VidgarVii commented on app/models/user.rb
> +        .joins(questions: :answers)
есть таблица "юзерс", есть таблица "тестс"
на втором занятии разбирались со списком сущностей и там упоминалась сущность "результаты" (или как-то еще могли назвать, не помню как конкретно у тебя получилось)
таблица "результаты" должна быть связующей между "юзерс" и "тестс"
когда "юзер" проходит "тест" в ней должна появляться запись
это так называемая связующая таблица
мне кажется в скринкастах упоминались связующие таблицы
но в любом случае можешь поискать объяснения, документацию в интернете
минимальная связующая таблица должна содержать 3 поля: ай-ди (собственное), ай-ди первой таблицы, ай-ди второй таблицы (т.е. праймари ключ и два внешних ключа)
вот с помощью такой таблицы будет правильно решать данную задачку

2023-05-10 14:21 UTC, VidgarVii requested changes

2023-05-10 14:21 UTC, VidgarVii commented on db/migrate/20230509125238_remove_user_id_from_tests.rb
> +    remove_reference :tests, :user
не проще было откатить прошлую миграцию и удалить ту миграцию из данного МР? Сейчас эти 2 файла абсолютно не нужны в проекте

2023-05-10 14:24 UTC, VidgarVii requested changes
.

2023-05-10 15:26 UTC, prototype2010 commented on db/migrate/20230509125238_remove_user_id_from_tests.rb
> +    remove_reference :tests, :user
знаю, но я хочу так, чтобы уметь разгребать и сложные ситуации

2023-05-10 17:48 UTC, prototype2010 commented on db/migrate/20230506103449_add_user_id_to_test.rb
> +    add_reference :tests, :user, foreign_key: true, null: false
удалил эту

2023-05-11 05:06 UTC, VidgarVii requested changes

2023-05-11 05:06 UTC, VidgarVii commented on app/models/test.rb
> +        AND categories.title = '#{category_title}'")
выражение после and уже отвечает за выборку данных. Ему не место в joins. За это отвечает метод where

2023-05-11 05:06 UTC, VidgarVii commented on app/models/test.rb
> +          .order('tests.title': :desc)
про символы и то что должен вернуть метод by_category_title я уже писал ранее

2023-05-11 05:06 UTC, VidgarVii commented on app/models/user.rb
> +      AND results.user_id = #{id}
то же самое. Надо разделять логику слияние таблиц и выборку данных. Не надо всё в 1 кучу класть

2023-05-11 05:06 UTC, VidgarVii commented on db/migrate/20230509125401_add_user_id_to_answer.rb
> +  end
не исправлено

2023-05-11 05:06 UTC, VidgarVii commented on db/seeds.rb
> +               ])
теперь уже понятно что тут и сколько создаётся.
Для возможности тестирования для тестов надо создать по больше вопросов.Тест с 1 вопросом это какой-то странный тест. И для вопросов стоит добавить бо более вариантов ответов. До 4х.

2023-05-11 05:06 UTC, VidgarVii commented on db/seeds.rb
> +                 {user_id: user1.id, question_id: question1.id, correct: rand > 0.5 ? true : false},
А где текст ответа? И зачем тут юзер?
Юзер будет выбирать вариант ответа

2023-05-11 05:06 UTC, VidgarVii commented on db/seeds.rb
> +                 {user_id: user1.id, question_id: question1.id, correct: rand > 0.5 ? true : false},
rand > 0.5 ? true : false
Не зная за ранее правильный ответ, нам сложно будет тестировать приложение

2023-05-13 15:06 UTC, merged