scopes / validations
prototype2010/test-guru pull request #4
Opened 2023-05-17 19:00 UTC by prototype2010

2023-05-18 03:52 UTC, VidgarVii requested changes

2023-05-18 03:52 UTC, VidgarVii commented on app/models/category.rb
> +  default_scope -> { order(title: :desc) }
`default_scope` глобально меняет поведение всех запросов к модели
поэтому его [рекомендуют](https://github.com/rubocop-hq/rails-style-guide#macro-style-methods) записывать в самом верху класса

2023-05-18 03:52 UTC, VidgarVii commented on app/models/question.rb
> +  validates :answers, length: { minimum: 1, maximum: 4 }
валидация в модели Вопрос не будет препятствовать созданию новых ответов в количестве больше 4, потому что она не будет вызываться при добавлении новых ответов к вопросу

2023-05-18 03:52 UTC, VidgarVii commented on app/models/test.rb
> +  scope :correct_answers, lambda { |test_id|
1. в ТЗ про это не сказано
2. Скоуп по солглашению должен возвращать релейшены только той модели, у которых он вызывается. Подробнее ниже

2023-05-18 03:52 UTC, VidgarVii commented on app/models/test.rb
> +      .pluck(:title)
у скоупов есть важная особенность - они должны возвращать chainable объекты (объекты `ActiveRecord::Relation`)
благодаря этому с их использованием можно строить цепочки вызовов
скоупы можно чейнить с квери-методами  `ActiveRecord`, к примеру `where(level: ...).order(id: :desc).created_last_week ...`, с методами ассоциаций
квери-методы также возвращают объекты `ActiveRecord::Relation`
НО!
`pluck` вернет обычный массив, что нарушит эту конвенцию
поэтому, если скоуп должен вернуть объект или массив, но не `ActiveRecord::Relation`, то его лучше реализовывать обычными методами класса

2023-05-19 14:11 UTC, VidgarVii commented on app/models/answer.rb
> +  before_destroy :check_remained_answers_count
категорически не стоит так делать. Как тогада будем удалять вопрос?

2023-05-19 14:14 UTC, VidgarVii commented on app/models/answer.rb
> +  validates_with AnswerValidators::AnswerMaximumCountValidator, on: :create
для простых валидаций не стоит создавать отдельные классы. Это только усложняет чтение кода.
Это антипаттерн йо-йО

2023-05-19 14:15 UTC, VidgarVii commented on app/validators/answer_validators.rb
> +      return unless answer.question.answers.size >= MAX_ANSWERS
я бы скорее рекомендовал использовать в подобных валидациях `count` и проверку тогда надо записать `.count >= 4`
нас интересуют именно хранящиеся в базе ответы, точнее их количество
`size` же при наличии объектов в памяти берет их из памяти (а при отсутствии подгружает из базы)

в данном простом случае думаю оба варианта будут вести себя корректно, но в случае более сложной логики можно с `size` получить неожиданные ошибки

в памяти же может быть уже "перебор" (называется грязные данные) и объект не создастся, при этом в базе еще "недобор"

2023-05-19 14:24 UTC, VidgarVii commented on app/models/answer.rb
> +  scope :correct_only, -> { where(correct: true) }
Некоторые примеры по неймингу простых скоупов.
https://github.com/rubocop/rails-style-guide#named-scopes
Уточнение, конечно, всегда хорошо. Но тут уже есть устоявшиеся соглашение для булевых полей. Так же можно задать вопрос, а где скоуп где не только верные ответы?

2023-05-20 11:13 UTC, prototype2010 commented on app/models/answer.rb
> +  scope :correct_only, -> { where(correct: true) }
Для всех ответов - метод all

2023-05-21 06:16 UTC, merged