Views helpers / custom helpers
prototype2010/test-guru pull request #6
Opened 2023-05-26 07:22 UTC by prototype2010

2023-05-26 16:09 UTC, VidgarVii requested changes

2023-05-26 16:09 UTC, VidgarVii commented on app/views/layouts/application.html.erb
> +  <footer>
футер можно положить в паршал. 
shared/_footer.html.erb
И тут его рендерить.
Так этот файл будет чище

2023-05-26 16:09 UTC, VidgarVii commented on app/controllers/questions_controller.rb
>      if @question.save
не выполнено 
Список вопросов теста должен выводиться на той же странице, что и сам тест

2023-05-28 17:44 UTC, VidgarVii requested changes

2023-05-28 17:44 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +      render :show
после создания/обновления ресурса принято делать редирект на этот ресурс

2023-05-28 17:44 UTC, VidgarVii commented on app/helpers/application_helper.rb
> +    link_to author, "https://github.com/prototype2010/#{repo}"
не исправлено 
ссылки на внешние ресусры стоит открывать в новой вкладке

2023-05-28 17:44 UTC, VidgarVii commented on app/views/tests/show.erb
> +<%= render 'questions/questions_table', resource: @test.questions %>
важно:
ТЗ: "Список вопросов теста должен выводиться **на той же странице, что и сам тест**"
другими словами нужна страница для вывода теста
что приводит к следующим выводам:
- экшен `index` в классе `QuestionsController` лишний
- вызов коллбека для `index` не нужен
- список вопросов нужно выводить на странице теста
- путь `test_questions_path`, который ты используешь в экшенах, тоже лишний (нужно отменить его создание в `routes`)
- нужен контроллер для ресурса `:tests` (его написание было поэтапно продемонстрировано в скринкасте)

2023-05-28 17:44 UTC, VidgarVii commented on app/views/tests/_tests_table.erb
> +  <%= render Test.all  %>
Test.all вызывается несколько раз во вью.
Когда вью должен работать только с данными приходящими из контроллера

2023-05-28 17:44 UTC, VidgarVii commented on app/views/tests/_tests_table.erb
> +<table>
весь этот хтмл можно было написать в файле index.html.erb

2023-05-29 02:39 UTC, Grizzlybear87 commented
I need some help removing myself from a project?  Any help would be great 👍

2023-05-31 06:55 UTC, VidgarVii commented on app/views/questions/index.erb
> +<%= link_to 'To all tests', tests_path %>
этот файл не используется. Его тоже надо удалить

2023-05-31 07:06 UTC, merged